#!/usr/bin/env bash
# Ensures a root-level './gradlew' exists as a guard. Safe to run multiple times.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GRADLEW="$ROOT_DIR/gradlew"

if [ ! -f "$GRADLEW" ]; then
  echo "[ensure-gradlew] Creating guarded ./gradlew..."
  cat > "$GRADLEW" <<'EOF'
#!/usr/bin/env bash
# Guarded ./gradlew auto-generated by ensure-gradlew.sh
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$ROOT_DIR/notes_frontend"
REAL="$APP_DIR/android/gradlew"
if [ -f "$REAL" ]; then
  echo "[guard gradlew] Delegating to $REAL $*"
  chmod +x "$REAL"
  exec "$REAL" "$@"
else
  echo "[guard gradlew] No android/gradlew found. Skipping Gradle step ($*)."
  echo "[guard gradlew] Tip: cd notes_frontend && npm run prebuild:android"
  exit 0
fi
EOF
  chmod +x "$GRADLEW" || true
else
  echo "[ensure-gradlew] ./gradlew already present."
fi
