#!/usr/bin/env bash
# Helper to print guidance when CI tries to run ./gradlew but none exists.
echo "[gradlew-missing-help] This is an Expo-managed project. Native android/gradlew is generated by 'expo prebuild'."
echo "[gradlew-missing-help] Use guarded scripts: ./gradlew-ci, ./gradle-check.sh, or scripts/ci-gradle-wrapper.sh."
echo "[gradlew-missing-help] To enable native builds: cd notes_frontend && npm run prebuild:android"
exit 0
